- name: Fetch SC Task Data from ServiceNow
  hosts: localhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev121241.service-now.com"
    servicenow_user: "admin"
    servicenow_password: "U+$PZb6ikn3X"

    #servicenow_instance: "{{ snowurl_test }}"
    #servicenow_user: "{{ snowuser_test }}"
    #servicenow_password: "{{ snowpass_test }}"

    entire_values: []  # Initialize empty list here to hold the API responses

  tasks:
    - name: Base64 encode credentials
      set_fact:
        encoded_credentials: "{{ (servicenow_user ~ ':' ~ servicenow_password) | b64encode }}"
      no_log: true

    - name: Fetch SC Task - Main
      block:
        - name: Fetch SC Task
          uri:
            url: "{{ servicenow_instance }}/api/now/table/sc_task"
            method: GET
            headers:
              Accept: "application/json"
              Authorization: "Basic {{ encoded_credentials | string }}"
            return_content: yes
          register: sctask_data
          failed_when: sctask_data.failed  # Fail task if unable to connect API
      rescue:
        - name: Handle Block 1 Error
          debug:
            msg: "Error occurred while fetching sctask data - {{ sctask_data.failed }}"


    - name: Filter SCTasks with open state and SCTASK number
      set_fact:
        filtered_sctasks: "{{ sctask_data.json.result | selectattr('state', 'equalto', '1') | selectattr('number', 'match', '^SCTASK') | list }}"

    - name: Fail if no suitable SCTasks found
      fail:
        msg: "No SCTask found with either open state or number not starting with SCTASK"
      when: filtered_sctasks | length == 0

    - name: Print details
      debug:
        msg: "SCTask - Number: {{ item.number }}, Short Description: {{ item.short_description }}, Parent: {{ item.assignment_group.link }}"
      loop: "{{ sctask_data.json.result }}"
      loop_control:
        loop_var: item

    - name: Make API calls and get entire values-main
      block:
        - name: Make API calls and get entire values
          loop: "{{ filtered_sctasks }}"
          loop_control:
            loop_var: item
          include_tasks: get_api_response.yml
          vars:
            api_encoded_credentials: "{{ encoded_credentials }}"
            item: "{{ item }}"
          when:
            - item.state == "1"
            - item.number is match("^SCTASK")
      rescue:
        - name: Handle Block 2 -Make API calls and get entire values
          debug:
            msg: "Error occurred while getting RITM and request details"
  
    - name: Change SC Task State-main
      block:
        - name: Change SC Task State
          loop: "{{ entire_values }}"
          loop_control:
            loop_var: item1
          include_tasks: sctask_statusUpdate.yml
          vars:
            api_encoded_credentials1: "{{ encoded_credentials }}"
            item1: "{{ item1 }}"
            servicenow_instance1: "{{ servicenow_instance }}"
          when:
            - item1.sctask_data.state == "1"
            - item1.sctask_data.number is match("^SCTASK")
      rescue:
        - name: Handle Block - SCTASK Status change
          debug:
            msg: "Error occurred while changing the SCTASK status"
    
- name: Save entire_values to CSV file
  hosts: localhost
  tasks:
    - name: Save entire_values to CSV file
      ansible.builtin.file:
        path: "{{ playbook_dir }}/api_responses.csv"
        state: touch

    - name: Write entire_values to CSV file
      ansible.builtin.copy:
        content: "{{ entire_values | to_nice_json }}"
        dest: "{{ playbook_dir }}/api_responses.csv"

    - name: Debug Variables
      debug:
        var: playbook_dir

    - name: Iterate through entire_values
      loop: "{{ entire_values }}"
      set_fact:
        sctask_data: "{{ item.sctask_data }}"
        item_request_item_response: "{{ item.item_request_item_response }}"
        item_request_response: "{{ item.item_request_response }}"

    - name: Initialize filtered_data as an empty list
      set_fact:
        filtered_data: []

    - name: Add selected fields to filtered_data
      set_fact:
        filtered_data: "{{ filtered_data + [{
          'sctask_data': {
            'opened_at': item.sctask_data.opened_at,
            'cmdb_ci': (item.sctask_data.cmdb_ci.value | default('Attribute not found')),
            'short_description': item.sctask_data.short_description,
            'state': item.sctask_data.state,
            'sys_id': item.sctask_data.sys_id
          },
          'item_request_item_response': {
            'cat_item_value': (item.item_request_item_response.cat_item.value | default('Attribute not found')),
            'RITM':(item.item_request_item_response.number | default('Attribute not found'))
          },
          'item_request_response': {
            'REQ': (item.item_request_response.number | default('Attribute not found')),
            'requestedfor_req': (item.item_request_response.requested_for.value | default('Attribute not found'))
          }
        }] }}"
      loop: "{{ entire_values }}"
      loop_control:
        loop_var: item
    
    - name: Debug filtered_data
      debug:
        var: filtered_data

    - name: Connect DB and get ci details
      block:
        - name: Connect DB and get ci details
          loop: "{{ filtered_data }}"
          loop_control:
            loop_var: item1
          include_tasks: cmdbci_db.yml
          vars:
            dbhost: "database-1.cpt56hhgq7lv.ap-south-1.rds.amazonaws.com"
            cmdb_ci: "ANNIE-IBM"
            mysql_credentials:
                login_host: "{{ dbhost }}"
                login_user: "admin"
                login_port: "3306"
                login_password: "ansible123"
                login_db: "taskdata"
            item: "{{ item1 }}"

      rescue:
        - name: Connect DB and get ci details
          debug:
            msg: "Error occurred while connecting db and fetching details"
  
