---
- name: Launch Ansible Tower Job Template
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch Job Template
      awx.awx.awx_job_launch:
        tower_host: "35.154.24.128"
        tower_username: "selvi"
        tower_password: "selvi"
        validate_certs: false
        job_template: "install-selvi"
      register: job_launch_result
      
    - name: Display Job Details
      debug:
        var: job_launch_result
