---
- name: Fetch SC Task Data from ServiceNow
  hosts: localhost
  gather_facts: no

  vars:
    #servicenow_instance: "https://dev121241.service-now.com"
    #servicenow_user: "admin"
    #servicenow_password: "U+$PZb6ikn3X"

    servicenow_instance: "{{ snowurl_test }}"
    servicenow_user: "{{ snowuser_test }}"
    servicenow_password: "{{ snowpass_test }}"

  tasks:
    - name: Print the variable value
      debug:
        var: servicenow_user

    - name: Print the variable value
      debug:
        var: servicenow_instance
        
