- name: Fetch SC Task Data from ServiceNow
  hosts: localhost
  gather_facts: no
- name: Connect DB and get ci details
  block:
    - name: Connect DB and get ci details
      include_tasks: cmdbci_db.yml
      vars:
        dbhost: "database-1.cpt56hhgq7lv.ap-south-1.rds.amazonaws.com"
        mysql_credentials:
            login_host: "{{ dbhost }}"
            login_user: "admin"
            login_port: "3306"
            login_password: "ansible123"
            login_db: "taskdata"
            short_description: ""
            Description: ""
      register: task_final_output

  rescue:
    - name: Connect DB and get ci details
      debug:
        msg: "Error occurred while connecting db and fetching details"
