---
- name: Launch Ansible Tower Job Templates Dynamically
  hosts: localhost
  gather_facts: true
  tasks:
    - block:
      - name: print username #pass the variables
      - name: Divide filtered_sctasks into sets of 10 items
        set_fact:
          task_sets: "{{ desired_output | batch(10) | list }}"

      - name: Debug Desired Output
        debug:
          var: desired_output

      - name: Display task details
        debug:
          var: current_set

      - name: Trigger job templates in parallel for each set
        
      - name: Display item in the current set
        debug:
          var: item

      - name: Iterate over JSON objects in current_set and trigger job templates
        awx.awx.job_launch:
          tower_host: "35.154.24.128"  # Replace with your Tower host
          tower_username: "selvi"  # Replace with your Tower username
          tower_password: "selvi"  # Replace with your Tower password
          validate_certs: False
          job_template: "{{ item.usecase_template }}"
          extra_vars:
            task_data: "{{ item }}"
        loop: "{{ current_set }}"
        loop_control:
          loop_var: item
        when: current_set | default([]) | length > 0

