---
- name: Extract word after /si/ and get usecase id details
  hosts: localhost
  gather_facts: yes
  vars:
    Description: "{{ mysql_credentials.Description }}"

  tasks:
    - name: Extract word after /si/
      set_fact:
        extracted_word: "{{ Description.split('/si/')[1].split('/')[0] }}"

    - name: Display result
      debug:
        var: extracted_word

- name: Execute MySQL Query
  community.mysql.mysql_query:
    login_host: "{{ mysql_credentials.login_host }}"
    login_user: "{{ mysql_credentials.login_user }}"
    login_port: "{{ mysql_credentials.login_port }}"
    login_password: "{{ mysql_credentials.login_password }}"
    login_db: "{{ mysql_credentials.login_db }}"
    query: SELECT * FROM `templateID_details` where short_description LIKE '{{ short_description }}' AND site LIKE '{{ extracted_word }}';
  register: query_result_usecaseName

- name: Debug Query Result
  debug:
    var: query_result_usecaseName
    
- name: Debug Query Result
  debug:
    var: query_result

- name: Debug Query Result1
  debug:
     var: query_result.query_result[0][0].Template
     
